export const LOAD_SERVICES_REQUEST = 'LOAD_SERVICES_REQUEST';
export const LOAD_SERVICES_RESPONSE = 'LOAD_SERVICES_RESPONSE';

export const LOAD_SERVICE_DETAILS_REQUEST = 'LOAD_SERVICE_DETAILS_REQUEST';
export const LOAD_SERVICE_DETAILS_RESPONSE = 'LOAD_SERVICE_DETAILS_RESPONSE';

// fetcher
export const FETCH_START = 'FETCH_START';
export const FETCH_DONE = 'FETCH_DONE';
export const FETCH_ERROR = 'FETCH_ERROR';
